# Generated by Django 2.2 on 2019-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('category', 'engine', 'name', 'passengers', 'manufacturer')},
        ),
    ]
