# Generated by Django 2.2 on 2019-05-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('category', 'engine', 'name', 'passengers')},
        ),
    ]
