# Generated by Django 2.2 on 2019-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20190515_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('category', 'engine', 'name', 'passengers', 'manufacturer')},
        ),
    ]
